// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHsvmB2bzazXy-ZscJQ1vhvttowvMsuY',
    appId: '1:555378559886:web:ba1200ef76595301c8f2df',
    messagingSenderId: '555378559886',
    projectId: 'mindease-10d40',
    authDomain: 'mindease-10d40.firebaseapp.com',
    storageBucket: 'mindease-10d40.firebasestorage.app',
    measurementId: 'G-N7X4MQ25H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYydiKxO6Z8rh3HYlEhiREH2QzF7FsCM',
    appId: '1:555378559886:android:538c449027df3379c8f2df',
    messagingSenderId: '555378559886',
    projectId: 'mindease-10d40',
    storageBucket: 'mindease-10d40.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrHsvmB2bzazXy-ZscJQ1vhvttowvMsuY',
    appId: '1:555378559886:web:71767933daf107f6c8f2df',
    messagingSenderId: '555378559886',
    projectId: 'mindease-10d40',
    authDomain: 'mindease-10d40.firebaseapp.com',
    storageBucket: 'mindease-10d40.firebasestorage.app',
    measurementId: 'G-3LNRFHMV48',
  );
}
